// SPDX-License-Identifier: MIT OR Apache-2.0

//! Every source-like file in the repository must carry the SPDX licence header.

use std::fs;
use std::path::Path;

use crate::support::tools::repo_root;

const SPDX: &str = "SPDX-License-Identifier: MIT OR Apache-2.0";

/// Directories that hold generated or third-party content.
const SKIP_DIRS: &[&str] = &["target", ".git", ".idea", "corpus", "artifacts"];

/// Files that must stay verbatim (licence texts) or are generated by tools.
const SKIP_FILES: &[&str] = &["LICENSE-MIT", "LICENSE-APACHE", "Cargo.lock"];

const CHECKED_EXTENSIONS: &[&str] = &["rs", "toml", "md", "qc", "src", "ps1", "sh", "yml", "yaml"];

fn needs_header(path: &Path) -> bool {
    let name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
    if SKIP_FILES.contains(&name) {
        return false;
    }
    name == ".gitignore"
        || name == ".gitattributes"
        || path
            .extension()
            .and_then(|e| e.to_str())
            .is_some_and(|e| CHECKED_EXTENSIONS.contains(&e))
}

fn walk(dir: &Path, missing: &mut Vec<String>) {
    for entry in fs::read_dir(dir).unwrap() {
        let path = entry.unwrap().path();
        let name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
        if path.is_dir() {
            if !SKIP_DIRS.contains(&name) {
                walk(&path, missing);
            }
        } else if needs_header(&path) {
            let text = fs::read_to_string(&path).unwrap_or_default();
            let head: String = text.lines().take(3).collect::<Vec<_>>().join("\n");
            if !head.contains(SPDX) {
                missing.push(path.strip_prefix(repo_root()).unwrap().display().to_string());
            }
        }
    }
}

#[test]
fn every_file_has_an_spdx_header() {
    let mut missing = Vec::new();
    walk(repo_root(), &mut missing);
    missing.sort();
    assert!(missing.is_empty(), "files without `{SPDX}`:\n  {}", missing.join("\n  "));
}
