// SPDX-License-Identifier: MIT OR Apache-2.0

//! Every source-like file in the repository must carry the SPDX licence header and use LF line
//! endings.

use std::fs;
use std::path::{Path, PathBuf};

use crate::support::tools::repo_root;

const SPDX: &str = "SPDX-License-Identifier: MIT OR Apache-2.0";

/// Directories that hold generated or third-party content.
const SKIP_DIRS: &[&str] = &["target", ".git", ".idea", ".claude", "corpus", "artifacts"];

/// Files that must stay verbatim (licence texts) or are generated by tools.
const SKIP_FILES: &[&str] = &["LICENSE-MIT", "LICENSE-APACHE", "Cargo.lock"];

const CHECKED_EXTENSIONS: &[&str] =
    &["rs", "toml", "md", "qc", "qh", "src", "ps1", "sh", "py", "yml", "yaml", "expected"];

fn is_text(path: &Path) -> bool {
    let name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
    name == ".gitignore"
        || name == ".gitattributes"
        || SKIP_FILES.contains(&name)
        || path
            .extension()
            .and_then(|e| e.to_str())
            .is_some_and(|e| CHECKED_EXTENSIONS.contains(&e))
}

fn needs_header(path: &Path) -> bool {
    let name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
    let ext = path.extension().and_then(|e| e.to_str()).unwrap_or("");
    is_text(path) && !SKIP_FILES.contains(&name) && ext != "expected"
}

/// Text files in the repository.
fn text_files(dir: &Path, out: &mut Vec<PathBuf>) {
    for entry in fs::read_dir(dir).unwrap() {
        let path = entry.unwrap().path();
        let name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
        if path.is_dir() {
            if !SKIP_DIRS.contains(&name) {
                text_files(&path, out);
            }
        } else if is_text(&path) {
            out.push(path);
        }
    }
}

fn rel(path: &Path) -> String {
    path.strip_prefix(repo_root()).unwrap().display().to_string()
}

#[test]
fn every_file_has_an_spdx_header() {
    let mut files = Vec::new();
    text_files(repo_root(), &mut files);
    let mut missing: Vec<String> = files
        .iter()
        .filter(|p| needs_header(p))
        .filter(|p| {
            let text = fs::read_to_string(p).unwrap_or_default();
            let head: String = text.lines().take(3).collect::<Vec<_>>().join("\n");
            !head.contains(SPDX)
        })
        .map(|p| rel(p))
        .collect();
    missing.sort();
    assert!(missing.is_empty(), "files without `{SPDX}`:\n  {}", missing.join("\n  "));
}

/// Line feeds only: no carriage returns (Windows line endings), and no raw NUL bytes (escape
/// them in literals).
#[test]
fn text_files_use_lf_line_endings() {
    let mut files = Vec::new();
    text_files(repo_root(), &mut files);
    let mut bad: Vec<String> = files
        .iter()
        .filter(|p| fs::read(p).unwrap().iter().any(|&b| b == b'\r' || b == 0))
        .map(|p| rel(p))
        .collect();
    bad.sort();
    assert!(bad.is_empty(), "files with CR or NUL bytes:\n  {}", bad.join("\n  "));
}
