# SPDX-License-Identifier: MIT OR Apache-2.0
#
# Generates src/builtins/numbers.rs: FTE's builtin name -> number tables for CSQC, SSQC and
# menu progs, extracted from an `fteextensions.qc` platform dump (FTE's `pr_dumpplatform`).
# Only the interface facts (names and numbers) are taken; builtins declared `= #0:name` are
# resolved by name at load time and get no number.
#
# Usage: python scripts/gen-builtin-numbers.py path/to/fteextensions.qc > src/builtins/numbers.rs

import re
import sys

DECL = re.compile(r"\b([A-Za-z_][A-Za-z0-9_]*)\s*=\s*#(\d+)(?::([A-Za-z_][A-Za-z0-9_]*))?\s*;")
TARGETS = {
    "CSQC": {"CSQC"},
    "SSQC": {"SSQC", "QWSSQC"},
    "MENU": {"MENU"},
}


def evaluate(cond, defined):
    """Evaluates the simple `#if` expressions used by the dump."""
    expr = re.sub(r"defined\s*\(\s*(\w+)\s*\)", lambda m: str(m.group(1) in defined), cond)
    expr = expr.replace("||", " or ").replace("&&", " and ").replace("!", " not ")
    try:
        return bool(eval(expr, {"__builtins__": {}}, {"True": True, "False": False}))
    except Exception:
        return False


def extract(lines, defined):
    table = {}
    named = set()
    stack = [True]
    for raw in lines:
        line = raw.strip()
        if line.startswith("#ifdef"):
            stack.append(stack[-1] and line.split()[1] in defined)
            continue
        if line.startswith("#ifndef"):
            stack.append(stack[-1] and line.split()[1] not in defined)
            continue
        if line.startswith("#if"):
            stack.append(stack[-1] and evaluate(line[3:], defined))
            continue
        if line.startswith("#else"):
            parent = stack[-2] if len(stack) > 1 else True
            stack[-1] = parent and not stack[-1]
            continue
        if line.startswith("#endif"):
            if len(stack) > 1:
                stack.pop()
            continue
        if line.startswith("#define") or not stack[-1]:
            continue
        code = line.split("/*")[0].split("//")[0]
        for m in DECL.finditer(code):
            name, number, bound = m.group(1), int(m.group(2)), m.group(3)
            if number == 0:
                named.add(bound or name)
            else:
                table.setdefault(name, number)
    return table, named


def main():
    lines = open(sys.argv[1], encoding="latin-1").read().splitlines()
    out = []
    out.append("// SPDX-License-Identifier: MIT OR Apache-2.0")
    out.append("")
    out.append("//! FTE's builtin numbers, generated by `scripts/gen-builtin-numbers.py` from an")
    out.append("//! `fteextensions.qc` platform dump. Builtins FTE resolves by name (`#0:name`) are")
    out.append("//! listed separately and have no number.")
    out.append("")
    out.append("#![allow(clippy::unreadable_literal)]")
    for target, defined in TARGETS.items():
        defined = set(defined) | {"FTEDEP", "DEP"}
        table, named = extract(lines, defined)
        out.append("")
        out.append(f"/// `{target}` builtin numbers, sorted by name.")
        out.append(f"pub(crate) static {target}: &[(&str, u32)] = &[")
        for name in sorted(table):
            out.append(f'    ("{name}", {table[name]}),')
        out.append("];")
        out.append("")
        out.append(f"/// `{target}` builtins resolved by name, sorted.")
        out.append(f"pub(crate) static {target}_NAMED: &[&str] = &[")
        for name in sorted(named):
            out.append(f'    "{name}",')
        out.append("];")
    sys.stdout.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
